spring:
  application:
    name: mg-spring-cloud-service-api


server:
  port: 8762
  max-http-header-size: 20480


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
