
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
#      serviceId: mg-spring-cloud-service-api  #这里可以直接负载到指定生产者
      url: http://localhost:8763/
    api-b:
      path: /api/b/**
#      serviceId: mg-spring-cloud-service-api2
      url: http://localhost:8762/
  ignored-services: "*"  #忽略直接使用微服务名访问


